crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
]

library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('book-list/', views.BookListView.as_view(), name='book-list'),
    path('book-detail/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('book-create/', views.BookCreateView.as_view(), name='book-create'),
    path('book-update/<int:pk>/', views.BookUpdateView.as_view(), name='book-update'),
    path('book-delete/<int:pk>/', views.BookDeleteView.as_view(), name='book-delete'),

    path('category-list/', views.CategoryListView.as_view(), name='category-list'),
    path('category-detail/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category-create/', views.CategoryCreateView.as_view(), name='category-create'),
    path('category-update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category-update'),
    path('category-delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category-delete'),
]

library/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    category_name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('library:category-detail', kwargs={'pk': self.pk })


class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    book_detail = models.TextField(max_length=5000, default='Details not available')
    borrowed = models.BooleanField(default=False)

    def __str__(self):
        return self.book_name

    def get_absolute_url(self):
        return reverse('library:book-detail', kwargs={'pk': self.pk})

library/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView, TemplateView
from .models import Category, Book


class HomeView(TemplateView):
    template_name = 'library/home.html'


# Book
class BookCreateView(CreateView):
    model = Book
    template_name = 'forms/book_form.html'
    fields = ['category', 'book_name', 'author', 'book_detail']


class BookUpdateView(UpdateView):
    model = Book
    template_name = 'forms/book_form.html'
    fields = ['category', 'book_name', 'author', 'book_detail', 'borrowed']


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'forms/book_confirm_delete.html'
    success_url = reverse_lazy('library:book-list')


class BookListView(ListView):
    model = Book
    context_object_name = 'book_list'


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book_detail'

    # def get_queryset(self):
    #     return Book.objects.filter(id=self.pk)


# Category
class CategoryCreateView(CreateView):
    model = Category
    template_name = 'forms/category_form.html'
    fields = ['category_name']


class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'forms/category_form.html'
    fields = ['category_name']


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'forms/category_confirm_delete.html'
    success_url = reverse_lazy('library:category-list')


class CategoryListView(ListView):
    model = Category
    context_object_name = 'category_list'


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category_detail'

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Title {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <!--<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">-->
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{%url 'library:home'%}"> Brand </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{%url 'library:book-list'%}">All Books <span class="sr-only">(current)</span></a></li>
        <li><a href="{%url 'library:category-list'%}">All Categories </a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    {% block body %}
    {% endblock %}
</div>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
</body>

</html>

library/templates/forms/book_confirm_delete.html
{% extends 'base.html' %}


{% block body %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

library/templates/forms/book_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

library/templates/forms/category_confirm_delete.html
{% extends 'base.html' %}


{% block body %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

library/templates/forms/category_form.html
{% extends 'base.html' %}

{% block body %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

library/templates/library/book_detail.html
{% extends 'base.html' %}

{% block title %} Book Detail {% endblock %}

{% block body %}

<h1>Name - {{ book_detail.book_name}}</h1>
<h3>Category- {{ book_detail.category}}</h3>
<h3>Author - {{ book_detail.author}}</h3>
<h3>Book Detail - {{ book_detail.book_detail}}</h3>
<h3>Borrowed - {{ book_detail.borrowed }}</h3>

<a href= "{% url 'library:book-update' book_detail.pk %}"><button>Update </button></a>

<a href= "{% url 'library:book-delete' book_detail.pk %}"> <button>Delete </button></a>

{% endblock %}

library/templates/library/book_list.html
{% extends 'base.html' %}

{% block title %} Book List {% endblock %}

{% block body %}
    <a href="{% url 'library:book-create' %}"> <button>Create Book </button></a>
    <h1>All Books:</h1>
    {% for book in book_list %}
<br>
    <a href="{% url 'library:book-detail' book.pk %}"> <h2>{{ book.book_name }}</h2> </a>
    <h4>Category-  {{ book.category }} </h4>
    {% endfor %}

{% endblock %}

library/templates/library/category_detail.html
{% extends 'base.html' %}

{% block title %} Category Detail{% endblock %}


{% block body %}


<h1>Category Details:</h1>

<h2> Category Name - {{ category_detail.category_name  }}</h2>
<br>
    <a href="{% url 'library:category-update' category_detail.pk %}"> <button> Update </button> </a>

    <a href="{% url 'library:category-delete' category_detail.pk %}"> <button> Delete </button> </a>

<h3>Available books in this category: </h3>

{% for book in category_detail.book_set.all %}
    <a href="{% url 'library:book-detail' book.id %}"><h4> {{ book.book_name }}</h4></a>
{% endfor %}
<br>



{% endblock %}

library/templates/library/category_list.html
{% extends 'base.html' %}

{% block title %} Category list {% endblock %}

{% block body %}
<a href="{% url 'library:category-create' %}"> <button> Create Category </button></a>


    {% for category in category_list %}
    <br>
    <a href="{% url 'library:category-detail' category.pk %}"> <h1> {{ category.category_name }} </h1> </a>
    {% endfor %}


{% endblock %}

library/templates/library/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}

{% block body%}
    <h1>Hello this is home </h1>
    <a href="{% url 'library:book-list'%}"><h2>Book List </h2></a>
{% endblock %}